title: generic-analogue-digital
hero_image: images/banner.png
subtitle: generic-analogue-digital subtitle
description: generic-analogue-digital description
original_url: https://codeclubprojects.org/en-GB/scratch/rock-band
theme: cc-prototype
published: false
steps:
  - title: Step one
    duration: 60
