---
title: generic-analogue-digital
hero_image: images/banner.png
description: Η διαφορά μεταξύ αναλογικού και ψηφιακού
original_url:
theme: cc-prototype
duration: 1
ingredient: true
listed: false
copyedit: false
interests:
technologies:
steps:
  - 
    title: Αναλογικό και ψηφιακό
